const state={goal:5,progress:0,host:{id:null,name:'@host',avatar:null},challenger:null,turn:'challenger',board:Array(9).fill(null),active:false};
const $=s=>document.querySelector(s), board=$('#board');
function render(){board.innerHTML='';state.board.forEach((v,i)=>{const c=document.createElement('div');c.className=`cell ${v?v.toLowerCase():'empty'}`;c.dataset.number=i+1;c.textContent=v||'';board.appendChild(c)});$('#roseGoal').textContent=state.goal;$('#progressText').textContent=`${state.progress} / ${state.goal}`;$('#progressBar').style.width=`${Math.min(100,state.progress/state.goal*100)}%`;$('#hostName').textContent=state.host.name;setAvatar('#hostAvatar',state.host);if(state.challenger){$('#challengerName').textContent=state.challenger.name;setAvatar('#challengerAvatar',state.challenger)}$('#mission').style.display=state.active?'none':'block';$('#status').textContent=state.active?(state.turn==='challenger'?`VEZ DE ${state.challenger.name}`:'VEZ DO HOST'):'AGUARDANDO DESAFIANTE'}
function setAvatar(sel,u){const el=$(sel);if(u.avatar){el.style.background=`center/cover url("${u.avatar}")`;el.textContent=''}else{el.style.background='';el.textContent=(u.name||'?').replace('@','')[0]?.toUpperCase()||'?'}}
function startChallenger(user){state.challenger=user;state.active=true;state.turn='challenger';state.board.fill(null);state.progress=state.goal;render()}
function play(index,mark){if(index<0||index>8||state.board[index])return false;state.board[index]=mark;render();return true}
function onComment(e){if(!state.active||state.turn!=='challenger'||!state.challenger)return;if(String(e.userId)!==String(state.challenger.id))return;const n=Number(String(e.comment||'').trim());if(!Number.isInteger(n)||n<1||n>9)return;if(play(n-1,'O'))state.turn='host';render()}
function onGift(e){if(state.active)return;/* O Daniel deve enviar o progresso já normalizado pela regra configurada. */if(e.ruleId==='join_duel'){state.progress=Math.min(state.goal,Number(e.progress||0));if(e.completed)startChallenger({id:e.userId,name:e.username?.startsWith('@')?e.username:`@${e.username}`,avatar:e.avatar});render()}}
function setHost(e){state.host={id:e.userId,name:e.username?.startsWith('@')?e.username:`@${e.username}`,avatar:e.avatar};render()}
// Ponte pública para o Projeto Daniel. Mantém regra/configuração fora do jogo.
window.NOT_DUEL={configure({goal=5}={}){state.goal=goal;render()},event(e){if(!e)return;if(e.type==='host')setHost(e);if(e.type==='gift_progress')onGift(e);if(e.type==='comment')onComment(e)},hostPlay(n){if(state.active&&state.turn==='host'&&play(Number(n)-1,'X')){state.turn='challenger';render()}},reset(){state.active=false;state.challenger=null;state.progress=0;state.board.fill(null);render()}};
render();